In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import numpy as np

In [5]:
df = pd.read_csv("../data/ipl_2026_deliveries.csv")

In [9]:
df.head()

,match_id,season,phase,match_no,date,venue,batting_team,bowling_team,innings,over,...,bowler,runs_of_bat,extras,wide,legbyes,byes,noballs,wicket_type,player_dismissed,fielder
0,202601,2026,Group Stage,1,"Mar 28, 2026","M.Chinnaswamy Stadium, Bengaluru",SRH,RCB,1,0.1,...,Jacob Duffy,0,0,0,0,0,0,NaN,NaN,NaN
1,202601,2026,Group Stage,1,"Mar 28, 2026","M.Chinnaswamy Stadium, Bengaluru",SRH,RCB,1,0.2,...,Jacob Duffy,1,0,0,0,0,0,NaN,NaN,NaN
2,202601,2026,Group Stage,1,"Mar 28, 2026","M.Chinnaswamy Stadium, Bengaluru",SRH,RCB,1,0.3,...,Jacob Duffy,0,0,0,0,0,0,NaN,NaN,NaN
3,202601,2026,Group Stage,1,"Mar 28, 2026","M.Chinnaswamy Stadium, Bengaluru",SRH,RCB,1,0.4,...,Jacob Duffy,6,0,0,0,0,0,NaN,NaN,NaN
4,202601,2026,Group Stage,1,"Mar 28, 2026","M.Chinnaswamy Stadium, Bengaluru",SRH,RCB,1,0.5,...,Jacob Duffy,0,0,0,0,0,0,NaN,NaN,NaN

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17477 entries, 0 to 17476
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   match_id          17477 non-null  int64
 1   season            17477 non-null  int64
 2   phase             17477 non-null  object
 3   match_no          17477 non-null  int64
 4   date              17477 non-null  object
 5   venue             17477 non-null  object
 6   batting_team      17477 non-null  object
 7   bowling_team      17477 non-null  object
 8   innings           17477 non-null  int64
 9   over              17477 non-null  float64
 10  striker           17477 non-null  object
 11  bowler            17477 non-null  object
 12  runs_of_bat       17477 non-null  int64
 13  extras            17477 non-null  int64
 14  wide              17477 non-null  int64
 15  legbyes           17477 non-null  int64
 16  byes              17477 non-null  int64
 17  noballs           17477 non-null  int64
 18  wicket_type       879 non-null    object
 19  player_dismissed  875 non-null    object
 20  fielder           686 non-null    object
dtypes: float64(1), int64(10), object(10)
memory usage: 2.8+ MB

In [12]:
df.shape

(17477, 21)

In [13]:
df.columns

Index(['match_id', 'season', 'phase', 'match_no', 'date', 'venue',
       'batting_team', 'bowling_team', 'innings', 'over', 'striker', 'bowler',
       'runs_of_bat', 'extras', 'wide', 'legbyes', 'byes', 'noballs',
       'wicket_type', 'player_dismissed', 'fielder'],
      dtype='object')

In [14]:
df.isnull().sum()

match_id                0
season                  0
phase                   0
match_no                0
date                    0
venue                   0
batting_team            0
bowling_team            0
innings                 0
over                    0
striker                 0
bowler                  0
runs_of_bat             0
extras                  0
wide                    0
legbyes                 0
byes                    0
noballs                 0
wicket_type         16598
player_dismissed    16602
fielder             16791
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df['date'] = pd.to_datetime(df['date'])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17477 entries, 0 to 17476
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   match_id          17477 non-null  int64
 1   season            17477 non-null  int64
 2   phase             17477 non-null  object
 3   match_no          17477 non-null  int64
 4   date              17477 non-null  datetime64[ns]
 5   venue             17477 non-null  object
 6   batting_team      17477 non-null  object
 7   bowling_team      17477 non-null  object
 8   innings           17477 non-null  int64
 9   over              17477 non-null  float64
 10  striker           17477 non-null  object
 11  bowler            17477 non-null  object
 12  runs_of_bat       17477 non-null  int64
 13  extras            17477 non-null  int64
 14  wide              17477 non-null  int64
 15  legbyes           17477 non-null  int64
 16  byes              17477 non-null  int64
 17  noballs           17477 non-null  int64
 18  wicket_type       879 non-null    object
 19  player_dismissed  875 non-null    object
 20  fielder           686 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(10), object(9)
memory usage: 2.8+ MB

In [19]:
df['batting_team'] = df['batting_team'].str.strip()
df['bowling_team'] = df['bowling_team'].str.strip()
df['venue'] = df['venue'].str.strip()
df['striker'] = df['striker'].str.strip()
df['bowler'] = df['bowler'].str.strip()

In [20]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month_name()
df['day'] = df['date'].dt.day_name()

In [22]:
df['total_runs'] = df['runs_of_bat'] + df['extras']

In [23]:
df[['date', 'year', 'month', 'day', 'total_runs']].head()

        date  year  month       day  total_runs
0 2026-03-28  2026  March  Saturday           0
1 2026-03-28  2026  March  Saturday           1
2 2026-03-28  2026  March  Saturday           0
3 2026-03-28  2026  March  Saturday           6
4 2026-03-28  2026  March  Saturday           0

In [24]:
df.to_csv("IPL_2026_Cleaned.csv", index=False)

In [26]:
df.shape

(17477, 25)

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
df.isnull().sum()

match_id                0
season                  0
phase                   0
match_no                0
date                    0
venue                   0
batting_team            0
bowling_team            0
innings                 0
over                    0
striker                 0
bowler                  0
runs_of_bat             0
extras                  0
wide                    0
legbyes                 0
byes                    0
noballs                 0
wicket_type         16598
player_dismissed    16602
fielder             16791
year                    0
month                   0
day                     0
total_runs              0
dtype: int64